### ISSUE TITLE
 @htl JavaScript comments are being parsed incorrectly

### ISSUE THREAD

**Issue by paulbthub** [MechanicalRabbit/HypertextLiteral.jl#15]
Inside a cell that defines a function as @htl code, inside a <script> block, if the JavaScript comment marker // is used to comment out a line that contains eg $anything, the cell will throw an 'UndefVarError: anything not defined' error if anything doesn't exist. Corresponding syntax errors are also thrown by other $-expressions. Whereas my understanding would be that commenting out a line should stop the cell from evaluating and/or caring about any of these $-expressions.

(Originally posted as a pluto issue, https://github.com/fonsp/Pluto.jl/issues/1387  but moved here on request.)

**Comment by paulbthub** [comment]
> HypertextLiteral doesn't include a JavaScript parser, so it's completely unaware of comment blocks within `<script>` tag.

Hmm, that's strange, because *something* seems to be parsing them... (I originally thought this was a Pluto issue, but I was asked to move the issue over here.)

Anyway, for an example, I'm using the sample notebook ' Using JavaScript inside Pluto' and I'm editing the code inside the cell for ClickCounter (generic function with 2 methods). Specifically I'm inserting a line as shown below --

	button.addEventListener("click", (e) => {
		count += 1
		[inserted line goes here]
		// we dispatch the input event on the div, not the button, because 

If I insert `anything` and hit ctrl/s, the cell compiles without an error. But running the code (by hitting the click button) throws a console error: anything is not defined. All of this behavior seems reasonable.

If I insert `$anything`, then ctrl/s immediately produces an UndefVarError:anything not defined. This also seems reasonable.

If I insert `//anything` and hit ctrl/s, the cell compiles and runs without an error. Again this is what I would expect: `anything` is now behind the // comment marker and is therefore being ignored.

But if I insert `//$anything` and then hit ctrl/s, the comment marker has no effect and I still get an UndefVarError: anything not defined. This is *not* the behavior I would expect; I would expect anything behind the // comment marker to simply be treated as a comment and therefore ignored.

(tbh this still feels like it's a Pluto issue to me, but I was asked to post it here, so I did...)

**Comment by clarkevans** [comment]
I'm not sure why you'd expect different behavior. The purpose of HypertextLiteral is to do interpolation. In this case, you've got `$anything` in your content (irregardless of the JavaScript comment).  So, `@htl` is going to expand this to substitute `$anything` with the value of the `anything` variable.  It appears as if `anything` is not defined, hence you get `UndefVarError`.   If you wish a literal `$anything` to appear in your output, you should write `\$anything`.

**Comment by paulbthub** [comment]
Hmm, well I'm not trying to do interpolation or construct a literal, I'm just trying to emulate the ClickCounter example which explicitly says I 'can use JavaScript to write input widgets'. The ClickCounter example uses @htl and // comment markers, so I was doing the same. The comment markers definitely do *something* here, because if eg you remove them from the next line (ie // we dispatch the input event on the div, not the button, because ) then ctrl/s immediately throws console errors beginning with 'Couldn't execute script'. So most of the time they seem to be working exactly as I'd expect, ie turning everything behind them into a comment and making no attempt to parse it. But the dollarsign seems to break through this behavior; commenting it out -- ie putting it behind a comment marker -- has no effect.

I guess I'm saying that the comment marker should take priority.

This is an issue for me because when debugging etc, I routinely use comment markers to stop lines of code from executing. But in this case, the comment markers are *not* stopping some of the elements behind it from being parsed.

**Comment by clarkevans** [comment]
Rather than using `@htl("...")` why don't you try using `html"..."` instead? 

It's unreasonable to expect that the JavaScript content marker should affect processing in Julia, which occurs server side well before the JavaScript program is even sent to the browser. There are two execution contexts you're working with.  On the server side, you're working with Julia, this builds JavaScript that is then sent and interpreted by the browser. If you use `@htl` to construct the string literal containing JavaScript, you will experience this special treatment for `$` because that's what HypertextLiteral does.  This interpolation occurs well before anything happens in the browser.  The JavaScript comment marker is completely irrelevant in this context. Only after the string literal containing the JavaScript is constructed (e.g. after interpolation has occurred) does the browser receive your JavaScript program, and only then do the JavaScript comment markers affect the function of your program.  I hope this helps.

**Comment by clarkevans** [comment]
I'm replying here since this response seem to be specific to `@htl`.

> Although this appears to create an irreconcilable contradiction, I think it could be achieved if comment stripping was the first operation performed by whatever logic gets first shot at parsing the contents of the cell. However, I accept that this isn't going to happen; I can choose one behavior or the other, but I can't have both.

So, yes, within `<script>` tag one could have a mini-lexer that would scan `JavaScript` content looking for comment blocks, and then disabling `$` interpolation in those blocks.  However, this is additional code that would have to be written, documented, tested and maintained. But more importantly, I can see lots of cases where I do want interpolation within comments to happen, and hence it's not clear that people wouldn't want to interpolate within comment blocks. So, to address this, one would also need a flag, and providing flags for `@htl` has proven complex (do you use thread local storage? or do you create a macro that creates macros that creates functions?).  Even if I suddenly found time to implemented this, it'd increase the complexity of what is already a rather complicated machine with another set of behavior... and that decreases usability.

**Comment by paulbthub** [comment]
Hi Clark, 

Thanks for continuing with this.

The first thing I want to make clear though is that, contrary to what you said, I don't think any of this is in fact specific to @htl. Nor do I think that any of my comment-related issues should be the responsibility of, or managed by, the htl parser. For all the reasons you've mentioned -- and even though I can't actually think of any situations where it might be desirable to interpolate within a comment block(*) -- I agree that this would increase complexity and in any case be entirely the wrong approach.

What I would expect instead is that comment stripping is done by whatever logic is managing the Pluto cell. As I understand it, this kind of comment-stripping parsing -- and indeed syntax parsing/color highlighting in general -- must already be done dynamically (ie before hitting ctrl/s) in a Pluto cell that contains Julia code; this is why an unmatched parenthesis behind a Julia # comment marker *doesn't* disrupt bracket-pair highlighting.

But as you said, when it comes to html/htl comment markers, "the server side Julia program logic doesn't even consider them."

This for me is the essence of the issue: to me, this 'failure to consider' feels like a bug. But whether it's a bug or no, imo it would certainly be great if the server side Julia/Pluto logic *did* consider them!

What I would really like is for Pluto cells to perform the same dynamic operations on html as it  presently does for Julia, including the dynamic syntax highlighting. However, this is more than I would presume to ask for. I'd be happy simply for html comment stripping to be performed as the first operation after hitting ctrl/s. (With the important proviso that there also still be some way of passing function arguments into the html code.)

(*) The reason for this, in my understanding, is that the only purpose of any comment written inside an html (or htl) code block in a Pluto cell must be to document the code that's written there. This must be true because as far as I know this is the only place that these comments are ever even visible/seen. According to where they appear in the HTML document, these comments use the appropriate comment markers, /*, // or <!, to ensure that they are not subsequently interpreted as code -- but their purpose (ie documentation of the html code within the Pluto cell) has already been fulfilled, hasn't it? If this is true, then they can safely be discarded/stripped *before* the code is passed on to the html or htl parser.
